version: "3.9"
services:
  db:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret123
      MYSQL_DATABASE: nestjs_development
    volumes:
      - db_data:/var/lib/mysql
  adminer:
    image: adminer:latest
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
volumes:
  db_data:
